settings:
  name: "BlueXP volume caching"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false

sidebar:
  entries:
    - title: BlueXP volume caching docs
      url: /index.html
    - section: release-notes
    - section: get-started
    - section: use
    - section: support
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: All BlueXP documentation

