---
sidebar: sidebar
permalink: get-started/cache-setup.html
keywords: bluexp, volume caching, 
summary: To use BlueXP volume caching, perform a few steps to set it up.    
---

= Set up BlueXP volume caching
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
To use BlueXP volume caching, perform a few steps to set it up.  


* Review link:../get-started/dr-prerequisites.html[prerequisites] to ensure that your environment is ready.
* Create a BlueXP Connector. 
* Create working environments.



== Set up in BlueXP
The next step is to set up volume caching in BlueXP. 


=== Create a Connector in BlueXP
You need to sign up for the beta or reach out to your NetApp Sales rep to try out this service. Then, when you use the BlueXP Connector, it will include the appropriate capabilities for the volume caching service. 

To create a Connector in BlueXP before using the service, refer to the BlueXP documentation that describes https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html[how to create a connector^]. 


== Create working environments 

If you haven’t done so already, you need to create the working environments for the source and target in the data replication relationship. 

* https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/start/task-getting-started-fsx.html[Create an Amazon FSx for ONTAP working environment^]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-aws.html[Launch Cloud Volumes ONTAP in AWS^] 
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html[Launch Cloud Volumes ONTAP in Azure^]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-gcp.html[Launch Cloud Volumes ONTAP in GCP^] 
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-adding-systems.html[Add existing Cloud Volumes ONTAP systems^]  
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html[Discover ONTAP clusters^] 




